[project]
name = "cse584"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "polars>=1.25.2",
    "pymilvus>=2.5.6",
    "tqdm>=4.67.1",
]
